### PR TITLE
Fix building on NetBSD

### PR DESCRIPTION
**Pull request by alarixbsd**
Just a simple case of using the code shared with macOS.

### CODE REVIEW

**Comment by NeoRaider** [comment]
Thanks! A few questions:
- Are both TUN and TAP modes working?
- Are the interfaces correctly removed when fastd is terminated?
- Do you know if needing to name interfaces `tunX` and `tapX` is a limitation of the NetBSD kernel, or if renaming could be supported in theory?

**Comment by alarixbsd** [comment]
I've only tested running with dropped privileges, which seems to involve fastd using an existing tap interface.

>     * Do you know if needing to name interfaces `tunX` and `tapX` is a limitation of the NetBSD kernel, or if renaming could be supported in theory?

The underlying device must be named the same as the kernel driver, i.e. `tunX` or `tapX`, but it can be assigned a 64 character description which will appear in ifconfig.

**Comment by NeoRaider** [comment]
I gave this a spin, and TAP mode is working great. TUN mode seems to need some more work (the TUNSIFHEAD ioctl might be related, currently checking this).

**Comment by NeoRaider** [comment]
Merged with a few additional fixes :)

**Comment by alarixbsd** [comment]
Awesome, thank you!

**Pull request merged**
